services:
  - type: web
    name: backend-buku-jabatan
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3005
